% Here I wanted to explain in more detail how errors estimates for totals
% generally work.  Each error structure contains basic error information,
% such as the U error, V error, UV covariance and some measure of the
% total error.  In both makeTUV and the OMA fit functions, these are
% generated by basic error propagation of some measure of radial
% uncertainty to the final total current product.  The differences lie in
% how these radial uncertainties are determined.  
%
% For makeTUV, the following possibilities are currently available: GDOP,
% GDOPMaxOrthog and GDOPRadErr (FitDif is also an error measurement, but it
% is not from error propagation and is quite different from the others and
% will not be discussed here).  G.D.O.P refers to geometric dillusion of
% precision and refers to the general uncertainty due to the limited angle
% coverage of the radials.  All makeTUV errors include this angle error in
% some way.  However, they make different assumptions about the radial
% uncertainties and the covariance between radial uncertainties.  In GDOP,
% all angles are used and each radial is assumed to have an uncertainty of
% 1.  In GDOPMaxOrthog, only the most orthogonal pair of angles is used and
% the radial uncertainty is 1.  This is basically equivalent to assuming
% that all uncertainties in other radial measurements are completely
% correlated with the two most orthogonal radials.  See
% totals/gdop_max_orthog for more details. GDOPRadErr uses all radial
% measurements, but includes a non-uniform radial uncertainty through the
% measured radial uncertainty in the Error variable in RADIAL structures.
% It assumes this error is in velocity units (i.e., cm/s or something like
% that).
%
% For OMA error measurements, see OMA/README_error_estimates
%
% The units of the reported errors are important.  Uerr, Verr and
% UVCovariance are reported in units of velocity^2 (typically cm2/s2).
% For historical and usability reasons, total errors are reported in
% units of velocity (cm/s).  Note that the UVCovariance represents the
% covariance between an individual U measurement and its corresponding V
% measurement.  There could also be covariance between current
% measurement uncertainties at different grid points, but this is not
% reported due to the large amount of disk space involved in saving the
% entire covariance matrix.
%
% Finally, note that the TotalErrors are generally the square-root of the
% maximum eigenvalue of the 2x2 UV covariance matrix.  This is generally
% considered the norm of the covariance matrix and is therefore a suitable
% measure of the total uncertainty.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% 	$Id: README_error_estimates.m 291 2007-02-28 22:08:48Z dmk $	
%
% Copyright (C) 2007 David M. Kaplan
% Licence: GPL (Gnu Public License)
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

help(mfilename)

