% Functions in this directory pertain principally to the generation of total
% currents from radial currents by the standard inversion method. There are
% also functions for manipulating such data. Totals data is stored in a
% uniform structure format that is created by the function TUVstruct.  This
% TUV structure is designed to be uniform enough that it provides a standard
% format for totals data, but flexible enough that it can contain additional
% information that might be particular to one instrument or type of totals
% processing. There are several basic assumptions underlying that TUV
% structure format.  These are explained below:
%
% 1) U, V fields sizes: U and V should be two dimensional arrays, with one
%    row for each grid point and one column for each timestep.
%
% 3) Other field sizes: LonLat should be [Num Spatial Grid Points x 2]. 
%    Similarly for the Depth.  TimeStamp should be [1 x Num Time Steps].
%
% 3) ErrorEstimates: This may be empty, but can also be an array of
%    structures of the format generated by TUVerrorstruct.  Each error
%    structure will have a standard set of variables, most of which have
%    the same size as U and V.
%
% 4) OtherMatrixVars: This is initially empty, but can be a structure
%    containing variables of the same size as U (i.e., they should be two
%    dimensional with size = [Num Spatial Grid Points x Num Time Steps].
%    Some functions, like subsrefTUV can optionally deal with the variables
%    inside this structure just like they do U and V.
%
% 4) OtherSpatialVars: This is initially empty, but can be a structure
%    containing variables of the same type as LonLat (i.e., they should of
%    size = [Num Spatial Grid Points x N], where N is an arbitrary number of
%    columns. Some functions, like subsrefTUV can optionally deal with the
%    variables inside this structure just like they do LonLat.
%
% 4) OtherTemporalVars: This is initially empty, but can be a structure
%    containing variables of the same type as TimeStamp (i.e., they should
%    of size = [N x Num Time Steps], where N is an arbitrary number of
%    rows. Some functions, like subsrefTUV can optionally deal with the
%    variables inside this structure just like they do TimeStamp.  Note that
%    the orientation of these variables is important.
%
% 5) OtherMetadata: This is initially empty, but can be a free-form
%    structure that contains additional information regarding the data.
%
% 6) Bad or missing data: This should be indicated by an NaN in the
%    appropriate place of U and V.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% 	$Id: README.m 191 2007-02-12 20:38:56Z dmk $	
%
% Copyright (C) 2007 David M. Kaplan
% Licence: GPL (Gnu Public License)
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

help README
